In [2]:
import pandas as pd
import numpy as np

In [5]:
movies_df = pd.read_csv('Movie.csv')
movies_df.head()

userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [6]:
movies_df.shape
#from the above dataframe there is not 8992 user ids, because one userid can watch other movie also and he can rate also

(8992, 3)

In [8]:
len(movies_df.userId.unique())

4081

In [16]:
print(movies_df.movie.unique())

['Toy Story (1995)' 'Jumanji (1995)' 'Grumpier Old Men (1995)'
 'Waiting to Exhale (1995)' 'Father of the Bride Part II (1995)'
 'Heat (1995)' 'Sabrina (1995)' 'Tom and Huck (1995)'
 'Sudden Death (1995)' 'GoldenEye (1995)']


In [18]:
#vector dimension = userId
#items(columns) = movies
user_movies_df = movies_df.pivot(index='userId',
                                columns='movie',
                                values='rating').reset_index(drop=True)

In [19]:
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
0                                     NaN               NaN   
1                                     NaN               NaN   
2                                     NaN               NaN   
3                                     NaN               4.0   
4                                     NaN               NaN   
...                                   ...               ...   
4076                                  4.0               NaN   
4077                                  3.5               NaN   
4078                                  NaN               3.0   
4079                                  NaN               NaN   
4080                                  NaN               NaN   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
0                          NaN          NaN             3.5             NaN   
1                          4.0          NaN             NaN             NaN   
2                          NaN          NaN             NaN             NaN   
3                          NaN          3.0             NaN             NaN   
4                          NaN          NaN             3.0             NaN   
...                        ...          ...             ...             ...   
4076                       NaN          NaN             NaN             NaN   
4077                       NaN          NaN             NaN             NaN   
4078                       4.0          5.0             NaN             3.0   
4079                       NaN          NaN             NaN             NaN   
4080                       NaN          NaN             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
0                      NaN                  NaN               NaN   
1                      NaN                  NaN               NaN   
2                      NaN                  NaN               4.0   
3                      NaN                  NaN               NaN   
4                      NaN                  NaN               NaN   
...                    ...                  ...               ...   
4076                   NaN                  NaN               NaN   
4077                   NaN                  NaN               4.0   
4078                   1.0                  NaN               4.0   
4079                   NaN                  NaN               5.0   
4080                   NaN                  NaN               4.5   

movie  Waiting to Exhale (1995)  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
4076                        NaN  
4077                        NaN  
4078                        NaN  
4079                        NaN  
4080                        NaN  

[4081 rows x 10 columns]

In [22]:
user_movies_df.index = movies_df.userId.unique()
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     NaN               NaN   
6                                     NaN               NaN   
8                                     NaN               NaN   
10                                    NaN               4.0   
11                                    NaN               NaN   
...                                   ...               ...   
7044                                  4.0               NaN   
7070                                  3.5               NaN   
7080                                  NaN               3.0   
7087                                  NaN               NaN   
7105                                  NaN               NaN   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          NaN          NaN             3.5             NaN   
6                          4.0          NaN             NaN             NaN   
8                          NaN          NaN             NaN             NaN   
10                         NaN          3.0             NaN             NaN   
11                         NaN          NaN             3.0             NaN   
...                        ...          ...             ...             ...   
7044                       NaN          NaN             NaN             NaN   
7070                       NaN          NaN             NaN             NaN   
7080                       4.0          5.0             NaN             3.0   
7087                       NaN          NaN             NaN             NaN   
7105                       NaN          NaN             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      NaN                  NaN               NaN   
6                      NaN                  NaN               NaN   
8                      NaN                  NaN               4.0   
10                     NaN                  NaN               NaN   
11                     NaN                  NaN               NaN   
...                    ...                  ...               ...   
7044                   NaN                  NaN               NaN   
7070                   NaN                  NaN               4.0   
7080                   1.0                  NaN               4.0   
7087                   NaN                  NaN               5.0   
7105                   NaN                  NaN               4.5   

movie  Waiting to Exhale (1995)  
3                           NaN  
6                           NaN  
8                           NaN  
10                          NaN  
11                          NaN  
...                         ...  
7044                        NaN  
7070                        NaN  
7080                        NaN  
7087                        NaN  
7105                        NaN  

[4081 rows x 10 columns]

In [24]:
#Impute those NaNs with 0 values
user_movies_df.fillna(0, inplace=True)
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     0.0               0.0   
6                                     0.0               0.0   
8                                     0.0               0.0   
10                                    0.0               4.0   
11                                    0.0               0.0   
...                                   ...               ...   
7044                                  4.0               0.0   
7070                                  3.5               0.0   
7080                                  0.0               3.0   
7087                                  0.0               0.0   
7105                                  0.0               0.0   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          0.0          0.0             3.5             0.0   
6                          4.0          0.0             0.0             0.0   
8                          0.0          0.0             0.0             0.0   
10                         0.0          3.0             0.0             0.0   
11                         0.0          0.0             3.0             0.0   
...                        ...          ...             ...             ...   
7044                       0.0          0.0             0.0             0.0   
7070                       0.0          0.0             0.0             0.0   
7080                       4.0          5.0             0.0             3.0   
7087                       0.0          0.0             0.0             0.0   
7105                       0.0          0.0             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      0.0                  0.0               0.0   
6                      0.0                  0.0               0.0   
8                      0.0                  0.0               4.0   
10                     0.0                  0.0               0.0   
11                     0.0                  0.0               0.0   
...                    ...                  ...               ...   
7044                   0.0                  0.0               0.0   
7070                   0.0                  0.0               4.0   
7080                   1.0                  0.0               4.0   
7087                   0.0                  0.0               5.0   
7105                   0.0                  0.0               4.5   

movie  Waiting to Exhale (1995)  
3                           0.0  
6                           0.0  
8                           0.0  
10                          0.0  
11                          0.0  
...                         ...  
7044                        0.0  
7070                        0.0  
7080                        0.0  
7087                        0.0  
7105                        0.0  

[4081 rows x 10 columns]

In [25]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [26]:
user_similarity = 1 - pairwise_distances(user_movies_df.values, metric='cosine')

In [28]:
print(user_similarity)

[[1.         0.         0.         ... 0.         0.         0.55337157]
 [0.         1.         0.         ... 0.45883147 0.         0.        ]
 [0.         0.         1.         ... 0.45883147 1.         0.62254302]
 ...
 [0.         0.45883147 0.45883147 ... 1.         0.45883147 0.47607054]
 [0.         0.         1.         ... 0.45883147 1.         0.62254302]
 [0.55337157 0.         0.62254302 ... 0.47607054 0.62254302 1.        ]]


In [31]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_similarity,)
user_sim_df

0         1         2         3         4         5         6     \
0     1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
1     0.000000  1.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
2     0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
3     0.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
4     1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4077  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
4078  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
4079  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
4080  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          7         8         9     ...      4071      4072      4073  \
0     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
1     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
3     0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
4     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4077  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
4078  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
4079  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
4080  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          4074      4075      4076      4077      4078      4079      4080  
0     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
1     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
2     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
3     0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
4     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
4076  0.000000  0.000000  1.000000  0.658505  0.000000  0.000000  0.000000  
4077  0.532152  0.000000  0.658505  1.000000  0.345306  0.752577  0.468511  
4078  0.324443  0.648886  0.000000  0.345306  1.000000  0.458831  0.476071  
4079  0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
4080  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  1.000000  

[4081 rows x 4081 columns]

In [32]:
#Set the index and colum names to user ids
user_sim_df.index = movies_df.userId.unique()
user_sim_df.columns = movies_df.userId.unique()

In [39]:
user_sim_df.iloc[0:5, 0:5]
#here 3 and 11 are similar so we can recommand mutually

3    6    8    10   11
3   1.0  0.0  0.0  0.0  1.0
6   0.0  1.0  0.0  0.0  0.0
8   0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  1.0  0.0
11  1.0  0.0  0.0  0.0  1.0

In [45]:
np.fill_diagonal(user_similarity, 0)
user_sim_df.iloc[0:5, 0:5]

3    6    8    10   11
3   0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0
11  1.0  0.0  0.0  0.0  0.0

In [46]:
#Most similar Users
user_sim_df.idxmax(axis=1)[0:10]
#these two columns are almost similar so they can mutually recommend

3       11
6      168
8       16
10    4047
11       3
12    6676
13    5953
14    4138
16       8
19    3603
dtype: int64

In [48]:
movies_df[(movies_df['userId']==6) | (movies_df['userId']==168)]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
60       168         Toy Story (1995)     4.5
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [55]:
user_1 = movies_df[movies_df['userId']==6]
user_2 = movies_df[movies_df['userId']==168]

In [56]:
user_2.movie

60    Toy Story (1995)
Name: movie, dtype: object

In [57]:
user_1.movie

1              Toy Story (1995)
3725    Grumpier Old Men (1995)
6464             Sabrina (1995)
Name: movie, dtype: object

In [58]:
pd.merge(user_1,user_2, on='movie', how='outer')
#by merging on=movies means common(joining for both) for 2 users movies and how=outer means keep as sepperate columns,outer=inner means only shows the known values
#so userId 11 didn't watch the movies Grumpier Old Men (1995) & Sabrina (1995)	so we can suggest that based on userId 6

userId_x                    movie  rating_x  userId_y  rating_y
0         6         Toy Story (1995)       5.0     168.0       4.5
1         6  Grumpier Old Men (1995)       3.0       NaN       NaN
2         6           Sabrina (1995)       5.0       NaN       NaN

In [59]:
pd.merge(user_1,user_2, on='movie', how='inner')


userId_x             movie  rating_x  userId_y  rating_y
0         6  Toy Story (1995)       5.0       168       4.5