In [1]:
#Univariate Feature Selection
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [2]:
names = ['preg', 'plas','pres','skin','test','mass','pedi','age','class']
dataframe = pd.read_csv('pima-indians-diabetes.data (1).csv',names=names)
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [7]:
dataframe.isnull().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   preg    768 non-null    bool 
 1   plas    768 non-null    bool 
 2   pres    768 non-null    bool 
 3   skin    768 non-null    bool 
 4   test    768 non-null    bool 
 5   mass    768 non-null    bool 
 6   pedi    768 non-null    bool 
 7   age     768 non-null    bool 
 8   class   768 non-null    bool 
dtypes: bool(9)
memory usage: 6.9 KB


In [6]:
x = dataframe.iloc[:,0:8]
y = dataframe.iloc[:,8]
x

preg  plas  pres  skin  test  mass   pedi  age
0       6   148    72    35     0  33.6  0.627   50
1       1    85    66    29     0  26.6  0.351   31
2       8   183    64     0     0  23.3  0.672   32
3       1    89    66    23    94  28.1  0.167   21
4       0   137    40    35   168  43.1  2.288   33
..    ...   ...   ...   ...   ...   ...    ...  ...
763    10   101    76    48   180  32.9  0.171   63
764     2   122    70    27     0  36.8  0.340   27
765     5   121    72    23   112  26.2  0.245   30
766     1   126    60     0     0  30.1  0.349   47
767     1    93    70    31     0  30.4  0.315   23

[768 rows x 8 columns]

In [8]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

In [10]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from numpy import set_printoptions
test = SelectKBest(score_func=chi2, k=5)#k should be >=0, <= n_features = 8; got 10. Use k='all' to return all features.
fit = test.fit(x,y)
set_printoptions(precision=4)
print(fit.scores_)

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [25]:
x = pd.DataFrame(fit.scores_).T
x.columns=names[:8]
x

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

In [36]:
#Recursive Feature Elimination
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
dataframe = pd.read_csv('pima-indians-diabetes.data (1).csv',names=names)
array = dataframe.values
x = array[:,0:8]
y = array[:,8]
model = LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(x,y)
print(fit.ranking_)

[1 1 3 5 4 1 1 2]


In [27]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [28]:
fit.n_features_

4

In [32]:
x = pd.DataFrame(fit.ranking_).T
x.columns=names[:8]
x

preg  plas  pres  skin  test  mass  pedi  age
0     1     1     3     5     4     1     1    2

In [41]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x,y)
print(model.feature_importances_)

[0.0514 0.325  0.0966 0.0207 0.0295 0.2236 0.1277 0.1254]


In [43]:
x = pd.DataFrame(model.feature_importances_).T
x.columns = names[:8]
x

preg      plas      pres      skin      test      mass      pedi  \
0  0.051421  0.325004  0.096633  0.020705  0.029536  0.223612  0.127659   

       age  
0  0.12543